In [2]:
import pandas as pd

In [17]:
df=pd.read_csv("../data/features_v1.csv")
df.head()

   home_form  away_form  home_goal_diff  away_goal_diff    result  target
0   0.333333   0.666667            -0.4             1.2  away_win       2
1   0.866667   0.266667             2.2            -0.8  home_win       0
2   0.266667   1.000000            -1.8             4.4  home_win       0
3   0.800000   0.400000             3.6            -1.6  home_win       0
4   0.000000   0.400000            -3.8            -1.2  away_win       2

In [18]:
mapping = {
    "home_win": 0,
    "draw": 1,
    "away_win": 2
}

df["target"] = df["result"].map(mapping)

In [5]:
df.head()

   home_form  away_form  home_goal_diff  away_goal_diff    result  target
0   0.333333   0.666667            -0.4             1.2  away_win       2
1   0.866667   0.266667             2.2            -0.8  home_win       0
2   0.266667   1.000000            -1.8             4.4  home_win       0
3   0.800000   0.400000             3.6            -1.6  home_win       0
4   0.000000   0.400000            -3.8            -1.2  away_win       2

In [19]:
X = df[
    [
        "home_form",
        "away_form",
        "home_goal_diff",
        "away_goal_diff"
    ]
]

y = df["target"]

In [20]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

**Random forest on features v1**

In [8]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [9]:
from sklearn.metrics import accuracy_score

preds = rf.predict(X_test)

accuracy = accuracy_score(y_test, preds)

print("Accuracy:", accuracy)

Accuracy: 0.45809881175734835

In [10]:
from sklearn.metrics import classification_report

print(
    classification_report(
        y_test,
        preds
    )
)

              precision    recall  f1-score   support

           0       0.55      0.64      0.59      4684
           1       0.26      0.20      0.23      2206
           2       0.40      0.36      0.37      2704

    accuracy                           0.46      9594
   macro avg       0.40      0.40      0.40      9594
weighted avg       0.44      0.46      0.45      9594

In [11]:
importance = pd.DataFrame({
    "feature": X.columns,
    "importance": rf.feature_importances_
})

importance.sort_values(
    "importance",
    ascending=False
)

          feature  importance
3  away_goal_diff    0.286779
2  home_goal_diff    0.285864
0       home_form    0.216696
1       away_form    0.210661

**Logistic Regression on features V1**

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

lr_preds = model.predict(X_test)

In [22]:
from sklearn.metrics import accuracy_score

print(
    accuracy_score(
        y_test,
        lr_preds
    )
)

0.5310610798415677

In [ ]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, preds)

array([[2995,  759,  930],
       [1227,  439,  540],
       [1257,  486,  961]])

**logistic regression on features V2A**

In [2]:
df = pd.read_csv("../data/features_v2A.csv")

In [5]:
df.head()

,home_form,away_form,home_goal_diff,away_goal_diff,home_avg_scored,away_avg_scored,home_avg_conceded,away_avg_conceded,result,target
0,0.333333,0.666667,-0.4,1.2,1.4,2.6,1.8,1.4,away_win,2
1,0.866667,0.266667,2.2,-0.8,2.8,1.6,0.6,2.4,home_win,0
2,0.266667,1.000000,-1.8,4.4,1.4,5.0,3.2,0.6,home_win,0
3,0.800000,0.400000,3.6,-1.6,5.0,2.0,1.4,3.6,home_win,0
4,0.000000,0.400000,-3.8,-1.2,0.2,2.8,4.0,4.0,away_win,2

In [4]:
mapping = {
    "home_win": 0,
    "draw": 1,
    "away_win": 2
}

df["target"] = df["result"].map(mapping)

In [9]:
X= df[["home_form","away_form","home_goal_diff","away_goal_diff","home_avg_scored","away_avg_scored","home_avg_conceded","away_avg_conceded"]]

y= df["target"]

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('lr', LogisticRegression(max_iter=1000))])

In [13]:
lr_preds = model.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,lr_preds))

0.5317907025224098

**random_forest on features V2**

In [15]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

rf.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [16]:
pred = rf.predict(X_test)

In [17]:
print(accuracy_score(y_test,pred))

0.48665832812174276

**logistic regression on feature v2B**

In [2]:
df = pd.read_csv("../data/features_v2B.csv")

In [4]:
df.head()

,home_form,away_form,home_goal_diff,away_goal_diff,home_avg_scored,away_avg_scored,home_avg_conceded,away_avg_conceded,result,form_diff,goal_diff_diff,scored_diff,conceded_diff,target
0,0.333333,0.666667,-0.4,1.2,1.4,2.6,1.8,1.4,away_win,-0.333333,-1.6,-1.2,0.4,2
1,0.866667,0.266667,2.2,-0.8,2.8,1.6,0.6,2.4,home_win,0.600000,3.0,1.2,-1.8,0
2,0.266667,1.000000,-1.8,4.4,1.4,5.0,3.2,0.6,home_win,-0.733333,-6.2,-3.6,2.6,0
3,0.800000,0.400000,3.6,-1.6,5.0,2.0,1.4,3.6,home_win,0.400000,5.2,3.0,-2.2,0
4,0.000000,0.400000,-3.8,-1.2,0.2,2.8,4.0,4.0,away_win,-0.400000,-2.6,-2.6,0.0,2

In [3]:
mapping = {
    "home_win": 0,
    "draw": 1,
    "away_win": 2
}

df["target"] = df["result"].map(mapping)

In [5]:
X= df[["home_form","away_form","home_goal_diff","away_goal_diff","home_avg_scored","away_avg_scored","home_avg_conceded","away_avg_conceded",
       "form_diff","goal_diff_diff","scored_diff","conceded_diff"]]

y= df["target"]

In [6]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [24]:
model.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('lr', LogisticRegression(max_iter=1000))])

In [25]:
lr_pred = model.predict(X_test)

In [26]:
print(accuracy_score(y_test,lr_pred))

0.5314780070877632

**random forest on features v2B**

In [7]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200,random_state=42)

In [8]:
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [9]:
preds = rf.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,preds))

0.48551177819470503

**logistic regression on features_V2C**

In [23]:
df = pd.read_csv("../data/features_v2C.csv")

In [24]:
mapping = {
    "home_win": 0,
    "draw": 1,
    "away_win": 2
}

df["target"] = df["result"].map(mapping)

In [25]:
df.head()

   form_diff  goal_diff_diff  scored_diff  conceded_diff    result  target
0  -0.333333            -1.6         -1.2            0.4  away_win       2
1   0.600000             3.0          1.2           -1.8  home_win       0
2  -0.733333            -6.2         -3.6            2.6  home_win       0
3   0.400000             5.2          3.0           -2.2  home_win       0
4  -0.400000            -2.6         -2.6            0.0  away_win       2

In [26]:
X = df[["form_diff","goal_diff_diff","scored_diff","conceded_diff"]]
y = df["target"]

In [27]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [28]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('lr', LogisticRegression(max_iter=1000))])

In [29]:
lr_preds = model.predict(X_test)

In [30]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,lr_preds))

0.5326245570148009

**random forest on features v2C**

In [1]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=200,random_state=42)

In [14]:
rf.fit(X_train,y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [15]:
pred = rf.predict(X_test)

In [16]:
print(accuracy_score(y_test,pred))

0.48509485094850946

**logistic regression on features v3A**

In [3]:
df = pd.read_csv("../data/features_v3A.csv")

In [6]:
df.head()

,form_diff,goal_diff_diff,scored_diff,conceded_diff,result,home_elo,away_elo,elo_diff,target
0,-0.333333,-1.6,-1.2,0.4,away_win,1500.000000,1500.000000,0.000000,2
1,0.600000,3.0,1.2,-1.8,home_win,1500.000000,1500.000000,0.000000,0
2,-0.733333,-6.2,-3.6,2.6,home_win,1490.000000,1510.000000,-20.000000,0
3,0.400000,5.2,3.0,-2.2,home_win,1499.424989,1500.575011,-1.150023,0
4,-0.400000,-2.6,-2.6,0.0,away_win,1500.541911,1499.458089,1.083822,2

In [5]:
mapping = {
    "home_win": 0,
    "draw": 1,
    "away_win": 2
}

df["target"] = df["result"].map(mapping)

In [7]:
X = df[["form_diff","goal_diff_diff","scored_diff","conceded_diff","home_elo","away_elo","elo_diff"]]

y= df["target"]

In [8]:
from sklearn.model_selection import train_test_split

X_train ,X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [9]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("lr", LogisticRegression(max_iter=1000))
])

model.fit(X_train, y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('lr', LogisticRegression(max_iter=1000))])

In [10]:
pred = model.predict(X_test)

In [11]:
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test,pred))

0.5321033979570565

**logistic regression on features v3B**

In [12]:
df = pd.read_csv("../data/features_v3B.csv")

In [13]:
mapping = {
    "home_win": 0,
    "draw": 1,
    "away_win": 2
}

df["target"] = df["result"].map(mapping)

In [14]:
df.head()

   form_diff  goal_diff_diff   elo_diff    result  target
0  -0.333333            -1.6   0.000000  away_win       2
1   0.600000             3.0   0.000000  home_win       0
2  -0.733333            -6.2 -20.000000  home_win       0
3   0.400000             5.2  -1.150023  home_win       0
4  -0.400000            -2.6   1.083822  away_win       2

In [13]:
X = df[["form_diff","goal_diff_diff","elo_diff"]]

y= df["target"]

In [14]:
X_train ,X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [15]:
model.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('lr', LogisticRegression(max_iter=1000))])

In [16]:
preds = model.predict(X_test)

In [17]:
print(accuracy_score(y_test,preds))

0.530748384406921

In [25]:
X = df[["goal_diff_diff"]]

y= df["target"]

In [26]:
X_train ,X_test ,y_train ,y_test = train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [27]:
model.fit(X_train,y_train)

Pipeline(steps=[('scaler', StandardScaler()),
                ('lr', LogisticRegression(max_iter=1000))])

In [28]:
preds = model.predict(X_test)

In [29]:
print(accuracy_score(y_test,preds))

0.5290806754221389